name: release.yml
on:
  release:
    types: [ created ]


jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: vite build --mode production

      - name: Create release asset
        run: |
          mkdir -p release
          zip -r release/HKExpressDevelopmentTool.zip dist/ # 打包 dist 目录

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}